--CRIANDO A TABELA ESTILO
CREATE TABLE estilo(
IdEstilo INT IDENTITY PRIMARY KEY NOT NULL,
nome VARCHAR(70)
);

--CRIANDO A TABELA ARTISTAS
CREATE TABLE artistas(
IdArtista INT IDENTITY PRIMARY KEY NOT NULL,
IdEstilo INT FOREIGN KEY REFERENCES estilo (IdEstilo),
nome VARCHAR(90)
);

--CRIANDO A TABELA ALBUM
CREATE TABLE album(
IdAlbum INT IDENTITY PRIMARY KEY NOT NULL,
IdArtista INT FOREIGN KEY REFERENCES artistas (IdArtista),
nome VARCHAR(90),
datalancamento DATETIME,
localizacao VARCHAR(90),
qtdminutos VARCHAR(50),
);

--CRIANDO TABELA ESTILO ALBUM 
CREATE TABLE estiloalbum(
IdEstiloAlbum INT IDENTITY PRIMARY KEY NOT NULL,
IdAlbum INT FOREIGN KEY REFERENCES album (IdAlbum),
IdEstilo INT FOREIGN KEY REFERENCES estilo (IdEstilo),
);


--CRIANDO TABELA USUARIO
CREATE TABLE usuario(
IdUsuario INT IDENTITY PRIMARY KEY NOT NULL,
nome VARCHAR(70),
permissao VARCHAR(70),
senha VARCHAR(70),
email VARCHAR(70)
);